# Generated by Django 2.2.1 on 2019-06-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobtogether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingrequest',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '수락 대기중'), (2, '수락됨')], default=1),
        ),
        migrations.AlterField(
            model_name='matching',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '모집중'), (2, '만남 완료'), (3, '만남 실패')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
