# Generated by Django 2.2.1 on 2019-06-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobtogether', '0002_auto_20190607_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ifCheck',
            field=models.BooleanField(default=False),
        ),
    ]
