# Generated by Django 2.2.1 on 2019-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobtogether', '0002_auto_20190603_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='matching',
            name='maxage',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='matching',
            name='minage',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
