# Generated by Django 2.2.1 on 2019-06-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobtogether', '0004_auto_20190603_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='filter',
            new_name='keyword',
        ),
    ]
